//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDatatable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public string QuoteID { get; set; }
        public string CustomerName { get; set; }
        public string Description { get; set; }
        public double Quantity { get; set; }
        public double UnitPrice { get; set; }
        public double VatRate { get; set; }
        public double SubTotal { get; set; }
        public double TotalAmount { get; set; }
    }
}
